import: 
    - { path: /vendor/Cymbaline/Administration/config/parameters.yml }

parameters:
    env: dev
    baseurl: 
    basetitle: Cymbaline PHP Framework
    controllerdefault: Cdm/PronoBox/Defaut
    
    database:
        dev:
            host: localhost
            port: 
            dbname: alca
            dbuser: root
            dbpass: 
        prod:
            host: 
            port: 
            dbname: 
            dbuser: 
            dbpass: 
            
    
    roles:
        user: *
        admin: admin
    #tasks:
        #used: false
