parameters:
    env: dev
    baseurl: ~
    basetitle: DKs Fram 
    controllerdefault: Cdm/PronoBox/Defaut
    
    database:
        dev:
            host: localhost
            port: ~
            dbname: alca
            dbuser: root
            dbpass: ~
        prod:
            host: ~
            port: ~
            dbname: ~
            dbuser: ~
            dbpass: ~
            
    
    roles:
        user: *
        admin: admin
    