error:
    path: /error
    template: Cymbaline/Error/template/error
    controller: Cymbaline/Error/Error
    action: index
    
index:
    path: /
    template: Cymbaline/Generator/template/index
    controller: Cymbaline/Generator/Defaut
    action: index