error:
    path: /error
    template: Cymbaline/Error/template/fatal
    controller: Cymbaline/Error/Error
    action: index
    
index:
    path: /
    template: Cymbaline/Generator/template/index
    controller: Cymbaline/Generator/Defaut
    action: index
    
documentation:
    path: /documentation
    template: Documentation/index
    controller: Documentation/Defaut
    action: index

view:
    path: /view/get/path/string@path
    controller: Cymbaline/Administration/Defaut
    action: view

dbmanager:
    path: /sql/string@datas
    controller: core/component/dbmanager/DB
    action: sql