error:
    path: /error
    template: Cymbaline/Error/template/fatal
    controller: Cymbaline/Error/Error
    action: index
    
index:
    path: /
    template: Cymbaline/Generator/template/index
    controller: Cymbaline/Generator/Defaut
    action: index
    
documentation:
    path: /documentation
    template: Documentation/index
    controller: Documentation/Defaut
    action: index