error:
    path: /error
    template: Alca/ErrorBox/template/error
    controller: Alca/ErrorBox/Error
    action: index
    
index:
    path: /
    template: Alca/GenBox/template/index
    controller: Alca/GenBox/Defaut
    action: index