parameters:
    env: dev
    baseurl: 
    basetitle: 
    controllerdefault:
    path:
        www: /home/*****/
    
    database:
        dev:
            host: *****
            port: 
            dbname: *****
            dbuser: *****
            dbpass: *****
        prod:
            host: *****
            port: 
            dbname: *****
            dbuser: *****
            dbpass: *****
            
    
    roles:
        user: prono/
        manager: manager/
	
    community:	
	    member:
            authentification:
                exclude: [log,login,login_manager]
		    upload:
			    dir: public/upload/member/		
        manager:
            authentification:
                exclude: [log,login,login_manager]

    upload:
        valid:
            - jpg : image/jpeg
            - png : image/png
        size : 1024000

    api:
        used: true
        secret: *****
        identity: api_prono16		